import 'package:supabase_flutter/supabase_flutter.dart';

import '../data/column_names.dart';
import '../models/geography.dart';
import '../models/landmark_suggestion.dart';
import '../result.dart';

/// Zones and landmarks — the addressing layer the admin maintains.
///
/// Both lists are small and change rarely, so they are fetched whole rather than queried
/// per screen. On a weak connection, one cached list beats a fresh query every time.
abstract interface class GeographyRepository {
  Future<Result<List<Zone>>> zones({required String cityId, bool includeInactive});
  Future<Result<List<Landmark>>> landmarks({required String cityId});

  /// Creates or replaces. An empty id means create.
  Future<Result<Zone>> saveZone(Zone zone);

  /// Zones are deactivated, never deleted: past orders carry a `zoneId`, and deleting the
  /// zone would leave those addresses without the field a courier reads first.
  Future<Result<void>> setZoneActive(String zoneId, bool isActive);

  Future<Result<Landmark>> saveLandmark(Landmark landmark);

  /// Landmarks can be deleted outright. An address keeps the landmark *name* it was saved
  /// with, so removing a wrong entry costs no history.
  Future<Result<void>> deleteLandmark(String landmarkId);

  /// The landmarks customers typed themselves on recent orders, because the list did not
  /// have theirs. The raw material for [LandmarkSuggestion].
  Future<Result<List<LandmarkNote>>> landmarkNotes({
    required String cityId,
    int limit,
  });
}

class SupabaseGeographyRepository implements GeographyRepository {
  SupabaseGeographyRepository(this._db);

  final SupabaseClient _db;

  Zone _zone(Map<String, dynamic> row) => Zone.fromJson(ColumnNames.toModel(row));
  Landmark _landmark(Map<String, dynamic> row) =>
      Landmark.fromJson(ColumnNames.toModel(row));

  @override
  Future<Result<List<Zone>>> zones({
    required String cityId,
    bool includeInactive = false,
  }) {
    return Result.guard(() async {
      var query = _db.from('zones').select().eq('city_id', cityId);
      if (!includeInactive) {
        query = query.eq('is_active', true);
      }
      // Ordered by the database rather than in Dart: there is an index on
      // (city_id, sort_order), so this costs nothing and the list arrives ready.
      //
      // `ascending` is spelled out because postgrest-dart defaults it to *false* — the
      // opposite of what `order by` means in SQL, and of what the Firestore version did.
      // Left implicit, the admin's ordering comes back upside down.
      final rows = await query.order('sort_order', ascending: true);
      return rows.map(_zone).toList();
    });
  }

  @override
  Future<Result<List<Landmark>>> landmarks({required String cityId}) {
    return Result.guard(() async {
      final rows = await _db.from('landmarks').select().eq('city_id', cityId);
      return rows.map(_landmark).toList();
    });
  }

  @override
  Future<Result<Zone>> saveZone(Zone zone) {
    return Result.guard(() async {
      final row = ColumnNames.toRow(zone.toJson())..remove('id');
      // The key is generated by the table, so a create sends no id at all rather than an
      // empty string. `upsert` on a row with no id would insert a second one.
      final saved = zone.id.isEmpty
          ? await _db.from('zones').insert(row).select().single()
          : await _db.from('zones').update(row).eq('id', zone.id).select().single();
      return _zone(saved);
    });
  }

  @override
  Future<Result<void>> setZoneActive(String zoneId, bool isActive) {
    return Result.guard(
      () => _db.from('zones').update({'is_active': isActive}).eq('id', zoneId),
    );
  }

  @override
  Future<Result<Landmark>> saveLandmark(Landmark landmark) {
    return Result.guard(() async {
      final row = ColumnNames.toRow(landmark.toJson())..remove('id');
      final saved = landmark.id.isEmpty
          ? await _db.from('landmarks').insert(row).select().single()
          : await _db
              .from('landmarks')
              .update(row)
              .eq('id', landmark.id)
              .select()
              .single();
      return _landmark(saved);
    });
  }

  @override
  Future<Result<void>> deleteLandmark(String landmarkId) {
    return Result.guard(
      () => _db.from('landmarks').delete().eq('id', landmarkId),
    );
  }

  @override
  Future<Result<List<LandmarkNote>>> landmarkNotes({
    required String cityId,
    int limit = 500,
  }) {
    return Result.guard(() async {
      // Only the orders that carry a typed note. In Firestore this read every order in
      // the city and threw most of them away in Dart; here the database does the
      // discarding, and `limit` bounds what is genuinely useful rather than what fits.
      final rows = await _db
          .from('orders')
          .select('zone_id, address')
          .eq('city_id', cityId)
          .not('address->>landmarkNote', 'is', null)
          .limit(limit);

      final notes = <LandmarkNote>[];
      for (final row in rows) {
        final address = row['address'];
        if (address is! Map) continue;

        final note = address['landmarkNote'];
        // Orders that picked a listed landmark say nothing new; only the ones that had
        // to type their own are of any use here.
        if (note is! String || note.trim().isEmpty) continue;

        final zoneId = address['zoneId'] ?? row['zone_id'];
        if (zoneId is! String) continue;

        notes.add(LandmarkNote(zoneId: zoneId, text: note));
      }
      return notes;
    });
  }
}

/// In-memory geography, for tests and for building screens before the backend exists.
class FakeGeographyRepository implements GeographyRepository {
  FakeGeographyRepository({
    List<Zone> zones = const [],
    List<Landmark> landmarks = const [],
    List<LandmarkNote> notes = const [],
    this.failure,
  })  : _zones = List.of(zones),
        _landmarks = List.of(landmarks),
        _notes = List.of(notes);

  final List<Zone> _zones;
  final List<Landmark> _landmarks;
  final List<LandmarkNote> _notes;

  /// When set, every call fails with this, so the offline path can be exercised.
  final Failure? failure;

  int _nextId = 1;

  @override
  Future<Result<List<Zone>>> zones({
    required String cityId,
    bool includeInactive = false,
  }) async {
    if (failure != null) return Result.err(failure!);
    return Result.ok(
      _zones
          .where((z) => z.cityId == cityId && (includeInactive || z.isActive))
          .toList()
        ..sort((a, b) => a.sortOrder.compareTo(b.sortOrder)),
    );
  }

  @override
  Future<Result<List<Landmark>>> landmarks({required String cityId}) async {
    if (failure != null) return Result.err(failure!);
    return Result.ok(_landmarks.where((l) => l.cityId == cityId).toList());
  }

  @override
  Future<Result<Zone>> saveZone(Zone zone) async {
    if (failure != null) return Result.err(failure!);
    final saved = zone.id.isEmpty ? zone.copyWith(id: 'zone-${_nextId++}') : zone;
    _zones
      ..removeWhere((z) => z.id == saved.id)
      ..add(saved);
    return Result.ok(saved);
  }

  @override
  Future<Result<void>> setZoneActive(String zoneId, bool isActive) async {
    if (failure != null) return Result.err(failure!);
    final index = _zones.indexWhere((z) => z.id == zoneId);
    if (index < 0) return const Result.err(NotFoundFailure());
    _zones[index] = _zones[index].copyWith(isActive: isActive);
    return const Result.ok(null);
  }

  @override
  Future<Result<Landmark>> saveLandmark(Landmark landmark) async {
    if (failure != null) return Result.err(failure!);
    final saved =
        landmark.id.isEmpty ? landmark.copyWith(id: 'landmark-${_nextId++}') : landmark;
    _landmarks
      ..removeWhere((l) => l.id == saved.id)
      ..add(saved);
    return Result.ok(saved);
  }

  @override
  Future<Result<void>> deleteLandmark(String landmarkId) async {
    if (failure != null) return Result.err(failure!);
    _landmarks.removeWhere((l) => l.id == landmarkId);
    return const Result.ok(null);
  }

  @override
  Future<Result<List<LandmarkNote>>> landmarkNotes({
    required String cityId,
    int limit = 500,
  }) async {
    if (failure != null) return Result.err(failure!);
    return Result.ok(_notes.take(limit).toList());
  }
}
