"""Emit the Android resource tree for the launcher icon and the system splash.

Both are vector drawables built from the same flattened path the SVGs use, so the icon on
a phone and the icon in a print file are the same geometry. Legacy PNG mipmaps are
rasterised too, for devices below API 26.

The output lands in brand/android/ ready to copy into each app's
android/app/src/main/res/ — the three apps share it except for the package name.

    python brand/src/build_android.py
"""
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import build_logo as L
import flatten as F

SRC = Path(__file__).resolve().parent
RES = SRC.parent / "android" / "res"

# Legacy launcher sizes, and the 108dp adaptive foreground at the same densities.
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}


def write(rel, content):
    path = RES / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  res/{rel}")


def rasterise(svg_text, out_path, width, transparent):
    """One headless-Chrome shot. Shares the wrapper rules with export_png.py."""
    browser = next(
        (p for p in [
            Path(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
            Path(r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"),
            Path(r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"),
        ] if p.exists()), None)
    if browser is None:
        sys.exit("No Chrome or Edge found.")

    vb = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg_text)
    h = round(width * float(vb.group(2)) / float(vb.group(1)))
    svg_text = re.sub(r'\swidth="[\d.]+"\sheight="[\d.]+"', "", svg_text, count=1)
    svg_text = svg_text.replace("<svg ", f'<svg width="{width}" height="{h}" ', 1)
    bg = "transparent" if transparent else "#F5EBE2"

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        page = tmp / "p.html"
        page.write_text(
            "<!doctype html><meta charset='utf-8'>"
            f"<style>html,body{{margin:0;padding:0;background:{bg};overflow:hidden}}"
            "svg{display:block}</style>" + svg_text,
            encoding="utf-8",
        )
        shot = tmp / "s.png"
        cmd = [str(browser), "--headless", "--disable-gpu", "--hide-scrollbars",
               f"--screenshot={shot}", f"--window-size={width},{h}",
               f"--user-data-dir={tmp / 'profile'}"]
        if transparent:
            cmd.append("--default-background-color=00000000")
        cmd.append(page.as_uri())
        subprocess.run(cmd, capture_output=True, timeout=120)
        if not shot.exists():
            sys.exit(f"failed to rasterise {out_path.name}")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(shot), out_path)


def main():
    lam_d, lam_w, lam_h = L.outlines("ل")
    L.MARK_D = L.mark_path(lam_d, lam_w, lam_h)
    crumb_d = F.to_d(F.circle(*L.CRUMB))
    print(f"building android resources -> {RES}\n")

    # Adaptive icon ---------------------------------------------------------
    # The mark occupies 62 of the 108dp grid: inside the 66dp safe zone, so no launcher
    # mask can clip it. Foreground and background are separate layers by contract —
    # the launcher parallaxes them.
    fg_scale = 62 / 120
    off = (108 - 120 * fg_scale) / 2
    write("drawable/ic_launcher_foreground.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f'    <group android:name="mark" android:translateX="{off:.2f}" '
        f'android:translateY="{off:.2f}" android:scaleX="{fg_scale:.5f}" '
        f'android:scaleY="{fg_scale:.5f}">\n'
        f'        <path android:fillColor="{L.CREAM}" android:pathData="{L.MARK_D}" />\n'
        f'        <path android:fillColor="{L.ORANGE_LIGHT}" android:pathData="{crumb_d}" />\n'
        '    </group>\n'
        '</vector>\n'
    ))

    write("values/colors.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<resources>\n'
        f'    <color name="luqma_burgundy">{L.BURGUNDY}</color>\n'
        f'    <color name="luqma_cream">{L.CREAM}</color>\n'
        '</resources>\n'
    ))

    write("drawable/ic_launcher_background.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<shape xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <solid android:color="@color/luqma_burgundy" />\n'
        '</shape>\n'
    ))

    adaptive = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@drawable/ic_launcher_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
        '</adaptive-icon>\n'
    )
    write("mipmap-anydpi-v26/ic_launcher.xml", adaptive)
    write("mipmap-anydpi-v26/ic_launcher_round.xml", adaptive)

    # Themed icon: Android 13+ tints a single-colour version to the user's wallpaper,
    # so it must be one flat shape with no crumb.
    write("drawable/ic_launcher_monochrome.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f'    <group android:translateX="{off:.2f}" android:translateY="{off:.2f}" '
        f'android:scaleX="{fg_scale:.5f}" android:scaleY="{fg_scale:.5f}">\n'
        f'        <path android:fillColor="#FFFFFF" android:pathData="{L.MARK_D}" />\n'
        '    </group>\n'
        '</vector>\n'
    ))

    # System splash (API 31+) ----------------------------------------------
    # The icon Android draws lives in the middle 192dp of a 288dp canvas. Matching that
    # box exactly is what lets Flutter's first frame continue from the same position
    # instead of the mark jumping when the system splash hands over.
    splash_scale = 132 / 120
    soff = (288 - 120 * splash_scale) / 2
    write("drawable/ic_splash_mark.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="288dp" android:height="288dp"\n'
        '    android:viewportWidth="288" android:viewportHeight="288">\n'
        f'    <group android:translateX="{soff:.2f}" android:translateY="{soff:.2f}" '
        f'android:scaleX="{splash_scale:.5f}" android:scaleY="{splash_scale:.5f}">\n'
        f'        <path android:fillColor="{L.CREAM}" android:pathData="{L.MARK_D}" />\n'
        '    </group>\n'
        '</vector>\n'
    ))

    write("values-v31/styles.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<resources>\n'
        '    <style name="LaunchTheme" parent="@android:style/Theme.DeviceDefault.DayNight">\n'
        '        <item name="android:windowSplashScreenBackground">@color/luqma_burgundy</item>\n'
        '        <item name="android:windowSplashScreenAnimatedIcon">@drawable/ic_splash_mark</item>\n'
        '        <item name="android:windowSplashScreenIconBackgroundColor">@android:color/transparent</item>\n'
        '    </style>\n'
        '</resources>\n'
    ))

    # Pre-API-31 launch window: a burgundy field with the mark centred, so the handover
    # looks the same on older devices.
    write("drawable/launch_background.xml", (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by brand/src/build_android.py — do not edit by hand. -->\n'
        '<layer-list xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <item android:drawable="@color/luqma_burgundy" />\n'
        '    <item>\n'
        '        <bitmap android:gravity="center" android:src="@mipmap/ic_splash_mark" />\n'
        '    </item>\n'
        '</layer-list>\n'
    ))

    # Legacy raster mipmaps (API < 26) -------------------------------------
    icon_svg = (SRC.parent / "app_icon.svg").read_text(encoding="utf-8")
    mark_svg = (SRC.parent / "logo_mark_small.svg").read_text(encoding="utf-8")
    print()
    for density, factor in DENSITIES.items():
        px = round(48 * factor)
        rasterise(icon_svg, RES / f"mipmap-{density}" / "ic_launcher.png", px, True)
        rasterise(mark_svg, RES / f"mipmap-{density}" / "ic_splash_mark.png",
                  round(132 * factor), True)
        print(f"  mipmap-{density:<8} ic_launcher {px}px · ic_splash_mark {round(132 * factor)}px")


if __name__ == "__main__":
    main()
